version: '3.9'

services:
  pg-db:
    image: postgres
    restart: always
    volumes:
      - ./pg-init-scripts:/docker-entrypoint-initdb.d
    environment:
      - POSTGRES_MULTIPLE_DATABASES=db,db_test
      - POSTGRES_PASSWORD=1234
      - POSTGRES_USER=admin
    ports:
      - "5432:5432"