postgres:
  host: localhost
  port: 5432
  database: db
  user: admin
  password: 1234
  connect-timeout: 5s

downloader:
  file_folder: /home/home/go/github.com/BON4/go-employees/csv/

server:
  AppVersion: 1.0.0
  Port: :8080
  Mode: Development
  ReadTimeout: 5
  WriteTimeout: 5
  CtxDefaultTimeout: 12
  Debug: false