postgres:
  host: pg-db
  port: 5432
  database: db_test
  user: admin
  password: 1234
  connect-timeout: 5s

server:
  app_version: 1.0.0
  port: :8080
  mode: Development
  read_timeout: 5
  write_timeout: 5
  ctx_default_timeout: 12
  debug: true

logger:
  development: true
  level: info
